Añadir formulario C6 en la libCNMC
gisce/libCNMC pull request #538
Opened 2023-05-12 09:23 UTC by marcosfvilaboa

# Descripcion
- Añadir formulario C6 a la generación de ficheros de la `libCNMC`
# Ficheros modificados
- `libcnmc/cir_8_2021/FC6.py` (New)
- `libcnmc/cir_8_2021/__init__.py`
- `libcnmc/cli_8_2021.py`
- `libcnmc/utils.py`

2023-05-12 11:14 UTC, mameijeiras approved these changes

2023-05-12 13:15 UTC, ecarreras requested changes
Falta utilitzar la funció `utils.format_f` per tots els decimals

2023-05-12 13:16 UTC, ecarreras approved these changes
Ja he vist que es feia abans lo del format_f 👍🏻

2023-05-12 13:17 UTC, ecarreras approved these changes

2023-05-12 13:17 UTC, ecarreras commented
Corregeix conflictes i ja es pot mergejar

2023-05-16 09:08 UTC, mameijeiras approved these changes

2023-05-16 09:08 UTC, merged