A1: Opcion para extraer la tension del contrato
gisce/libCNMC pull request #664
Opened 2024-07-15 14:06 UTC by jgramos1997

# Para el versionado automático seleccionar uno de los siguientes labels:
- **major**: Major auto version vX._._
- **minor**: Minor auto version v_.X._
- **patch**: Patch auto version v_._.X

De esta forma el proceso de versionado se hará de forma automática

# Descripcion
- 

# Ficheros modificados
-

2024-07-16 15:44 UTC, marcosfvilaboa requested changes

2024-07-16 15:44 UTC, marcosfvilaboa commented on libcnmc/cir_8_2021/FA1.py
> +    def get_tensio(self, cup, year, tensio_modcon):
**`cup` Nooooooo `cups` always!!!!**

2024-07-17 08:22 UTC, marcosfvilaboa approved these changes

2024-07-18 13:15 UTC, ecarreras approved these changes

2024-07-18 13:15 UTC, merged